server:
  http:
    addr: 0.0.0.0:8001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s
  reg_dsn: 192.168.1.7:8500
  amqp_dsn: amqp://cwxu-algo:cwxu-algo@192.168.1.7:5672/algo
data:
  database:
    driver: postgres
    source: host=192.168.1.7 user=cwxu password=cwxu dbname=algo_core_data port=5432 sslmode=disable TimeZone=Asia/Shanghai
  redis:
    addr: 192.168.1.7:6379
    password: cwxu
    read_timeout: 0.2s
    write_timeout: 0.2s
