server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
  reg_dsn: 192.168.1.7:8500
data:
  database:
    driver: postgres
    source: host=192.168.1.7 user=cwxu password=cwxu dbname=algo_user port=5432 sslmode=disable TimeZone=Asia/Shanghai
  redis:
    addr: 192.168.1.7:6379
    password: cwxu
    read_timeout: 0.2s
    write_timeout: 0.2s
